### ISSUE TITLE
Should php closing tag be removed from the end of file

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#12]
Example:

```php
<?php posts_pagination( [
	'prev_text'       => __( '&larr; Previous' ),
	'next_text'       => __( 'Next &rarr;' ),
	'title_text'      => __( 'Posts Navigation' ),
	'container_class' => 'pagination pagination--posts',
	'title_class'     => 'pagination__title screen-reader-text'
] ) ?>
```

I think here are the [reason why it's recommended to remove php closing tag from the end of the file](https://softwareengineering.stackexchange.com/questions/89553/closing-tag-on-php-files), and sniff includes it.

**Comment by m-e-h** [comment]
@samikeijonen are you talking about the end of **_file_** ?

**Comment by justintadlock** [comment]
I assume you mean "files" and not "lines". :)

In normal PHP files, this is standard practice.

In templates, it's usually not a good leave off the trailing `?>`.  That's a _user-breaking-his-site-issue_ just waiting to happen.

**Comment by samikeijonen** [comment]
Yep, file:)

**Comment by samikeijonen** [comment]
In my opinion users are going to break child themes anyway, with or without closing `?>`. In worst case it might bring `headers already sent` issue.

**Comment by justintadlock** [comment]
From my understanding, because theme templates are always loaded after HTTP headers have already been sent, the headers already sent issue shouldn't be relevant.

I've never known this to be an issue within templates (maybe there is some edge case where it is; I don't know).  However, I have seen on many occasions users break things when by adding some HTML in a theme template where PHP wasn't closed.
