### ISSUE TITLE
Skip to content link is missing

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#18]
Skip to content link is missing from the `header/default.php`. Ideally it should actually be inside landmark region because [all content should be inside a landmark](https://make.wordpress.org/accessibility/handbook/best-practices/markup/aria-landmarks/).

I have it inside `<header>` at the moment. It could be inside it's own `<nav>` also.

[More info about skip links](https://make.wordpress.org/accessibility/handbook/best-practices/markup/skip-links/). If you ask me, I'm OK for dropping Javascript for IE11.

**Comment by justintadlock** [comment]
I was going to ask you about a skip link.  The following is a question I've had and haven't seen any answers about:

My thinking was that HTML5 was supposed to bring about a new era for accessibility where hacks like skip links were unnecessary.  The purpose of the `<main>` element was to always be the main content of the page.  Should screen readers not be able to simply skip to a site's main content on their own?  Otherwise, why not just use a `<div>` if `<main>` isn't actually helping us here?

**Comment by samikeijonen** [comment]
Good question. Skip link(s) main target group are keyboard users who probably don't use any AT devices. So they don't have shortcuts to `<main>` or other landmark regions.

**Comment by samikeijonen** [comment]
[From the screen reader survey](https://webaim.org/projects/screenreadersurvey7/#skip):

> It is important to note that while usage has decreased among screen reader users, "skip" links still provide notable benefit for other keyboard users.

**Comment by justintadlock** [comment]
> Good question. Skip link(s) main target group are keyboard users who probably don't use any AT devices. So they don't have shortcuts to `<main>` or other landmark regions.

Good answer. :)

**Comment by justintadlock** [comment]
Meant to tag this issue for the following commit: https://github.com/justintadlock/abc/commit/85f1cda410aba7c9bae4f8a489661779c2a0e6a5
